### PR TITLE
Add MIT license with copyright

### PR DESCRIPTION
**Pull request by manicmaniac**
Please choose your favorite license 📄

### CODE REVIEW

**Review by geckour — APPROVED** [review]
I think it's good to take MIT license since [original one](https://github.com/apollographql/frontpage-ios-app) has same one 👍 
Thanks!!

**Review by padobariya — APPROVED** [review]
Thank you! LGTM

**Review by oh-naoki — APPROVED** [review]
Thank you! 👍

**Comment by daisukefuji** [comment]
thank you @manicmaniac

**Pull request merged**
